name: medipal
description: "Medi-Pal"
publish_to: 'none' # private

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# dependencies
dependencies:
  flutter:
    sdk: flutter

  unicons: ^2.1.1
  table_calendar: ^3.1.0

  cloud_firestore: ^4.15.6
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.7
  
  bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4

  user_repository:
    path: packages/user_repository
  meta: ^1.11.0
  formz: ^0.7.0
  introduction_screen: ^3.1.12
  multi_state_bloc: ^0.0.4
  expandable_page_view: ^1.0.17
  go_router: ^13.2.0
  get_it: ^7.6.7
  dio: ^5.4.1
  hydrated_bloc: ^9.1.4

# dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logoApp.png"
  adaptive_icon_background: "#404776"
  adaptive_icon_foreground: "assets/images/logoApp.png"
  min_sdk_android: 21

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - "assets/images/logoApp.png"
    - "assets/images/mppurple.png"
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
